name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test (Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.17.3', '1.18.4']
        otp: ['26.0', '27.0']
        exclude:
          # OTP 27 requires Elixir 1.17+
          - elixir: '1.17.3'
            otp: '27.0'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run tests
      run: mix test

    - name: Generate coverage report
      run: mix coveralls.github
      if: matrix.elixir == '1.18.4' && matrix.otp == '27.0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.18.4']
        otp: ['27.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

    - name: Install dependencies
      run: MIX_ENV=dev mix deps.get

    - name: Compile (warnings as errors)
      run: MIX_ENV=dev mix compile --warnings-as-errors

    - name: Run Credo
      run: MIX_ENV=dev mix credo --strict

    - name: Cache PLT files
      uses: actions/cache@v4
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-plt-${{ matrix.elixir }}-${{ matrix.otp }}-

    - name: Run Dialyzer
      run: MIX_ENV=dev mix dialyzer
